services:
  db:
    image: mysql:8.0
    container_name: pokemon_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
      MYSQL_USER: pokemon
      MYSQL_PASSWORD: pokemon
    ports:
      - '3306:3306'
    volumes:
      - pokemon_db_data:/var/lib/mysql

volumes:
  pokemon_db_data:
