import { ElementsDataType } from '@/views/Home/model/types';

import {
  Bug,
  Dark,
  Dragon,
  Electric,
  Fairy,
  Fighting,
  Fire,
  Flying,
  Ghost,
  Grass,
  Ground,
  Ice,
  Normal,
  Poison,
  Psychic,
  Rock,
  Steel,
  Water,
} from '@/shared/ui';

export const elementsData: ElementsDataType[] = [
  { id: '1', name: 'elements.fire', color: 'var(--type-fire)', icon: <Fire /> },
  { id: '2', name: 'elements.water', color: 'var(--type-water)', icon: <Water /> },
  { id: '3', name: 'elements.grass', color: 'var(--type-grass)', icon: <Grass /> },
  { id: '4', name: 'elements.electric', color: 'var(--type-electric)', icon: <Electric /> },
  { id: '5', name: 'elements.ice', color: 'var(--type-ice)', icon: <Ice /> },
  { id: '6', name: 'elements.fighting', color: 'var(--type-fighting)', icon: <Fighting /> },
  { id: '7', name: 'elements.poison', color: 'var(--type-poison)', icon: <Poison /> },
  { id: '8', name: 'elements.ground', color: 'var(--type-ground)', icon: <Ground /> },
  { id: '9', name: 'elements.flying', color: 'var(--type-flying)', icon: <Flying /> },
  { id: '10', name: 'elements.psychic', color: 'var(--type-psychic)', icon: <Psychic /> },
  { id: '11', name: 'elements.bug', color: 'var(--type-bug)', icon: <Bug /> },
  { id: '12', name: 'elements.rock', color: 'var(--type-rock)', icon: <Rock /> },
  { id: '13', name: 'elements.ghost', color: 'var(--type-ghost)', icon: <Ghost /> },
  { id: '14', name: 'elements.dragon', color: 'var(--type-dragon)', icon: <Dragon /> },
  { id: '15', name: 'elements.steel', color: 'var(--type-steel)', icon: <Steel /> },
  { id: '16', name: 'elements.fairy', color: 'var(--type-fairy)', icon: <Fairy /> },
  { id: '17', name: 'elements.dark', color: 'var(--type-dark)', icon: <Dark /> },
  { id: '18', name: 'elements.normal', color: 'var(--type-normal)', icon: <Normal /> },
];
